/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jaja;

import org.junit.jupiter.api.Test;

import jaja.map.utils.Lerped;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        Lerped lerped = new Lerped(50, 0);

        System.out.println(lerped.lerp(0.5));

        // assertNotNull(lerped.lerp(0.5), "lerped");
    }
}
